[package]
name = "template"
version = "0.1.0"
authors = ["name <name@email.com>"]
edition = "2018"

[lib]
name = "template"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
