[package]
name = "estimate-pi"
version = "0.1.0"
edition = "2018"

[lib]
name = "estimate_pi"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies.rand]
version = "0.8.0"
features = ["small_rng"]

[dependencies.indicatif]
version = "0.15.0"